version = 1

test_patterns = ["what is my location?"]

exclude_patterns = ["love at last"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jquery"
  ]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "flow"
